### ISSUE TITLE
records for DOM events

### ISSUE THREAD

**Issue by kevinbarabash** [reasonml-community/bs-webapi-incubator#116]
I'm curious about the choice of functions to get event properties instead of passing recordings to event handlers.  I come from a JS background and find calling functions to access fields on events quite awkward.

**Comment by glennsl** [comment]
Hey. There's quite a few reasons why using records aren't a great idea:

1. It would mean converting every object to a record at runtime, and that has to be done with the whole object hierarchy which is often very large and usually recursive, which doesn't work very well with records. This also has a significant runtime cost, of course, and to make matters even worse, will add a lot of code. The library would most likely become an order of magnitude larger just because of this.

2. The DOM isn't well-typed, meaning the type of some object may not be known completely, and therefore can't be fully converted.

3. Records don't support subtyping, so you can't have functions operating on all kinds of events.

4. Records aren't objects. They don't have methods or internal mutable state. So the actual object would have to be carried around as an ordinary field in the record to be used by functions that would then delegate to the object methods internally. And if a method alters internal state, a new record would have to be created to reflect this new state, which would incur more runtime costs, but also means the API would have to diverge further from its JS counterpart, negating the purpose of using records in the first place.

5. Using functions to manipulate abstract types is more idiomatic. Hiding the structure of the data you're operating on is good practice because it affords you the flexibility of changing the implementation without changing the interface. This is why you have properties in C# and set/get methods in Java, for example, but in JavaScript good software engineering practices usually go out the window (which makes writing bindings for JS APIs often quite challenging).

Not all of these necessarily applies to DOM events specifically, but consistency across the whole of the DOM API is a goal in itself.

These reasons are just off the top of my head, so there may be more, but I hope this satisfies your curiosity at least :)
