### ISSUE TITLE
History

### ISSUE THREAD

**Issue by malthe** [reasonml-community/bs-webapi-incubator#119]
Shouldn't `History.state` be parameterized?

**Comment by glennsl** [comment]
I don't see how that would be sound, as it's a global object that can be accessed and manipulated anywhere. There's no way to guarantee that the things you pull out are the same things you put in.

The only safe way to go about this is to use the `Js.Types` API to introspect the runtime type and cast the values appropriately.

**Comment by erykpiast** [comment]
@glennsl How to write state through `History.pushState` in such a case? How to cast a meaningful OCaml type to `History.state`? The only thing I can do is `let historyState: History.state = [%raw "some JS object here"]`, but I don't know BuckleScript so much.

Ideally, I wish to have some domain structure, convert it to JS and use it as a state.
```ocaml
type historyState =
 { foo: string } [@@bs.deriving jsConverter]

let myHistoryState = { foo = "bar" };;

History.pushState (historyStateToJs myHistoryState) "updated state" "/path"
```
Does it make sense to you?

**Comment by glennsl** [comment]
The `pushState` API unfortunately isn't type-safe because the state can be "anything that is serializable", so the idea is that you would encapsulate it in such a way that you provide a safe API of your own and contain all the unsafety. So you could provide an API like this, for example:

```reason
module MyHistory : {
  type myState = ...;
  let pustState : (myState, string, string, History.t) => unit;
  let state : t => myState;
}
```

Then internally you need to convert `myState` to `History.state` and back again. Converting _to_ `History.state` is easy, you can just cast it using `%identity` and _assume_ it is serializable, because you control `myState` and ought to know whether or not it is:

```reason
external toState : myState => state = "%identity";
```

Going from `History.state` to `myState` is the tricky part, because you don't have exclusive control over `History.pushState` you can't know whether some other state has been pushed. The easiest way to do this is to use a data structure that is JSON-compatible and decode it using `Js.Json`, `bs-json` or whatever else you might prefer. Casting to `Js.Json.t` using `%identity` as above, is safe since that's also an unspecific type that does checks before using it. And once you have a `JsJson.t` value you can just decode as normal.

Hope that helps!

**Comment by erykpiast** [comment]
Alright, that clears things a lot for me, thank you!
