### ISSUE TITLE
Get the `detail` field from a custom event

### ISSUE THREAD

**Issue by nickretallack** [reasonml-community/bs-webapi-incubator#120]
Currently I'm using this:
```[@bs.get] external getEventDetail: Dom.event => Js.t({..}) = "detail";```

Perhaps this should be in bs-webapi?

**Comment by shtanton** [comment]
I'm trying to use this too, currently for web components.

I doubt it's possible to ensure safety as addEventListener can't change its type signature depending on whether it's listening for a custom event.

The best option I can think of is to accept an eventName type instead of a string for addEventListener:
`
type eventName =
  | Base(string)
  | Custom(string, 'a);
`
Or something to distinguish binding to regular events and custom events.

**Comment by glennsl** [comment]
How would you specify what `'a` is?

We could just add an `addCustomEventListener` as well:

    [@bs.send.pipe: t] external addCustomEventListener : string => (customEvent('a) => unit) => unit = "addEventListener";

But the problem remains, you still don't have a way of ensuring that `'a` is a concrete type.

Apart from that, we have to consider how to construct custom events and how to transition not having a type variable to having one, since the type actually lives in bs-platform, while the bindings live here.

**Comment by yawaramin** [comment]
Closing as I don't see a type-safe way to get the detail type from an `addEventListener` handler given our current bindings. This will probably require more specialized bindings for `addEventListener`, that constrain the type more for custom events.
