### ISSUE TITLE
Subtyping doesn't unify

### ISSUE THREAD

**Issue by Risto-Stevcev** [reasonml-community/bs-webapi-incubator#150]
I can't create a collection of various nodes like this:

```ocaml
let x =
  let document = Webapi.Dom.window |> Webapi.Dom.Window.document
  in
  [ Webapi.Dom.Document.createElement "foo" document
  ; Webapi.Dom.Document.createTextNode "bar" document ]
```

The subtyping fails, it doesn't compile

**Comment by Risto-Stevcev** [comment]
What's the current workaround for this right now?
I can't just use `appendChild`, I need an actual collection of `Dom.node_like`s

**Comment by glennsl** [comment]
I thought there was an `asNode` function in `Node`, which would be inherited by everything implementing it, but apparently there's not. I don't see why there couldn't be though, since there shouldn't be any overhead to a simple `external`.

Workaround would be something like:

    external asNode : Dom.node_like(_) => Dom.node = "%identity";

Want to add that in a PR?

**Comment by Risto-Stevcev** [comment]
Sure
I think it got removed as part of the new subtyping experiment:
https://github.com/reasonml-community/bs-webapi-incubator/commit/23423220a4359c700d27584aad80ec7d39b0525d#diff-57a44c44f32b358d6bc2e1bb952dffc2

**Comment by glennsl** [comment]
Right, I guess I figured it wouldn't be needed anymore. And it doesn't seem like it has been, until you got the bright idea to put them in collections :wink:
