### ISSUE TITLE
Function for converting Node to real type

### ISSUE THREAD

**Issue by mikaello** [reasonml-community/bs-webapi-incubator#152]
When you use e.g. `Element.querySelectorAll`, you get a `NodeList`, and converting this to an array of `Node`-type makes it impossible to further use e.g. `querySelector`, since this is a method of `Element` / `Document`, and not on `Node`. In JS is this not a problem, because you can use all methods of the real type (on your own risk, since they may not exist if the node is not the type you expect), but this is not possible in `bs-webapi`, as far as I could tell.

So could it be possible to add a function that converts a `Node`-type to its real type? E.g. something in the spirit of this:

```reason
type nodeConcrete =
  | Element(Dom.element)
  | Attribute(Dom.attr)
  | Text(Dom.text)
  | CDATASection(Dom.cdataSection)
  | EntityReference
  | Entity
  | ProcessingInstruction(Dom.processingInstruction)
  | Comment(Dom.comment)
  | Document(Dom.document)
  | DocumentType(Dom.documentType)
  | DocumentFragment(Dom.documentFragment)
  | Notation
  | Unknown;

let getNodeConreteType: Dom.node => nodeConcrete =
  node =>
    switch (Node.nodeType(node)) {
    | Element => Element(node)
    | Attribute => Attribute(node)
    | Text => Text(node)
    | CDATASection => CDATASection(node)
    | EntityReference => EntityReference
    | Entity => Entity
    | ProcessingInstruction => ProcessingInstruction(node)
    | Comment => Comment(node)
    | Document => Document(node)
    | DocumentType => DocumentType(node)
    | DocumentFragment => DocumentFragment(node)
    | Notation => Notation
    | Unknown => Unknown
    };
```

Then you could have 'switched' on `getNodeConreteType` and got the actual type. I don't if it is possible to just somehow coerce `Node`-type into the other types, or if this is against the type-system? Or is this not how it is intended to use `Node`?

**Comment by glennsl** [comment]
Hey. yeah, this should be possible, and a great idea I think. It does go against the type system, but that can be circumvented using `Obj.magic`, as long as you know what you're doing. You can see this same idea being used by [`Js.Types.classify`](https://github.com/BuckleScript/bucklescript/blob/master/jscomp/others/js_types.ml#L49-L78), for example.

I'm not entirely sure what the API for something like this should be, but I think I'd prefer a lightweight approach that uses polymorphic variants and leaves it outside the `Impl` functor so that it's not inherited by everything that implements the `Node` interface.

Feel free to try your hand at a PR for this, or continue to ask questions if you have them :)
