### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by dmartinjs** [reasonml-community/bs-webapi-incubator#153]
I think this project should probably call reason-web
as React bindings project is called reason-react
and React Native bindings is called reason-react-native.

It will be better for discoverability and naming conventions for primary usages such as Browser API, Nodejs API, React API and React Native API.

**Comment by glennsl** [comment]
It was originally called `reason-js`, but was renamed for a few different reasons:

- `bs-webapi` is BuckleScript-specific, but not Reason-specific, like `reason-react` and `reason-react-native` is due to their dependence on the JSX syntax. This library therefore follows the convention used by just about every other BuckleScript library of using the `bs-` prefix, such as `bs-node`, `bs-json` etc.

- BuckleScript covers the JS bindings, and this was meant as more of a temporary home for incomplete Web API bindings, which when more or less complete could be moved elsewhere. That hasn't exactly panned out though.

There might be a case to be made for providing a more integrated `reason-` prefixed ecosystem, but I don't think this is a good place to do it. Perhaps try [the forums](https://reasonml.chat/) of Discord. For discoverability specifically though, I think [redex](https://redex.github.io/) mostly solves that.

**Comment by dmartinjs** [comment]
Indeed,
if it target OCaml too,
it make sens.

Thanks for the answer.
