### ISSUE TITLE
Binding for XHR

### ISSUE THREAD

**Issue by Austaras** [reasonml-community/bs-webapi-incubator#177]
I don't know whether this is the proper place but there  still should be a binding for XHR although people don't use it often these days

**Comment by glennsl** [comment]
There is one here: https://github.com/stefanduberg/bs-xmlhttprequest. There's also [bs-fetch](https://github.com/reasonml-community/bs-fetch), which I'm sure you're aware of.

I don't see much value in bundling it here rather than having it as a separate library though, so I'll close this. But feel free to follow up if you have further questions or comments!
