### ISSUE TITLE
Upstream canvas bindings

### ISSUE THREAD

**Issue by chenglou** [reasonml-community/bs-webapi-incubator#72]
I've seen quite a few user land canvas bindings now, and upon perusing webapi's, I feel they're ready to be upstreamed? Tell me if I'm mistaken. Otherwise, great stuff once again, @glennsl @bloodyowl =D

Also, anyone dogfooding webGLRe.re?

**Comment by kevinbarabash** [comment]
@chenglou I'm just starting to play around with the bindings from Canvas2dRe.re.  The tests in https://github.com/reasonml-community/bs-webapi-incubator/blob/master/tests/canvas/canvas2d_test.re in use `|>` for some of the functions, but `|>` doesn't work consistently b/c many of the the function take the context as the first arg.  I'm curious about why the context isn't always the last arg.

**Comment by bloodyowl** [comment]
I think I have a couple of bindings locally (like `drawImage`), I'll put up a PR today

**Comment by wtfleming** [comment]
I took a shot at `drawImage` but it isn't quite right.

```reason
[@bs.send]
external drawImage :
  (
    t,
    ~image: HtmlImageElementRe.t,
    ~dx: float,
    ~dy: float,
    ~dWidth: float=?,
    ~dHeight: float=?,
    ~sx: float=?,
    ~sy: float=?,
    ~sWidth: float=?,
    ~sHeight: float=?,
    unit
  ) =>
  unit =
  "";
```

Not sure how to handle the image type since it can be any of the following:
`
An element to draw into the context. The specification permits any canvas image source (CanvasImageSource), specifically, a CSSImageValue, an HTMLImageElement, an SVGImageElement, an HTMLVideoElement, an HTMLCanvasElement, an ImageBitmap, or an OffscreenCanvas.
`
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

Working though this has been very educational in learning reason / converting some JS canvas code, but if you've already done the work, i'd love to see your PR @bloodyowl 

thanks!

**Comment by glennsl** [comment]
You can either make a separate binding for each type, use @bs.unwrap or a gadt with a phantom type. See https://github.com/glennsl/bucklescript-cookbook#bind-to-a-function-overloaded-to-take-an-argument-of-several-different-types-an-untagged-union

**Comment by yawaramin** [comment]
I think this repo has become the de facto home of the Web API bindings. We can always reopen if there is a desire to upstream into bs-platform.
